context:
  name: docling-ibm-models
  version: 2.0.4
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/docling_ibm_models-${{ version }}.tar.gz
  sha256: f21b68755ee253225c95b4710ec68eb575d7cdef4abe07ee9f13936e1c8f208d
  patches:
    - fix-numpy-dep.patch

build:
  number: 1
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    # We match the conda-forge python/numpy pinning.
    - ${{ "numpy =1.26" if match(python, ">=3.12") }}
    - ${{ "numpy =1.23" if match(python, "=3.11") }}
    - ${{ "numpy =1.22" if match(python, "=3.10") }}
    - ${{ "numpy =1.22" if match(python, "<=3.9") }}
    - torchvision
    - pytorch >=2.2.2,<3.0.0
    - jsonlines >=3.1.0,<4.0.0
    - pillow >=10.0.0,<11.0.0
    - tqdm >=4.64.0,<5.0.0
    - mean-average-precision >=2021.4.26.0
    - py-opencv >=4.6.0,<5.0.0
    - huggingface_hub >=0.23.0,<1.0.0

tests:
  - python:
      imports:
        - docling_ibm_models
      # `pip check` is disabled because:
      # - numpy 2.x: "numpy<2.0.0,>=1.24.4; python_version < "3.13", but you have numpy 2.1.3"
      # - false positive: "docling-ibm-models 2.0.4 has requirement mean_average_precision<2022.0.0.0,>=2021.4.26.0, but you have mean-average-precision 2024.1.5.0."
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: This package contains the AI models used by the Docling PDF conversion package
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/DS4SD/docling-ibm-models

extra:
  recipe-maintainers:
    - hadim
