context:
  name: docling-ibm-models
  version: 2.0.3
  python_min: "3.10" # remove this line once https://github.com/prefix-dev/rattler-build/pull/1122 is available

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/docling_ibm_models-${{ version }}.tar.gz
  sha256: 4ac155490a8646daca8aa7a45f0ee136ef96c4a0fbc24812694ec8fc45e5cadb

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - pytorch >=2.2.2
    - torchvision
    - numpy
    - lxml >=4.9.1
    - jsonlines >=3.1.0
    - pillow >=10.0.0
    - tqdm >=4.64.0
    - mean-average-precision >=2021.4.26.0
    - py-opencv >=4.6.0
    - huggingface_hub >=0.23

tests:
  - python:
      imports:
        - docling_ibm_models
      pip_check: false

about:
  summary: This package contains the AI models used by the Docling PDF conversion package
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/DS4SD/docling-ibm-models

extra:
  recipe-maintainers:
    - hadim
