context:
  name: docling-ibm-models
  version: "3.4.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/docling_ibm_models-${{ version }}.tar.gz
  sha256: f172334f4a723ad3ab91304d759ca887cce9f283179d60cc7c7167d920b57909
  patches:
    - fix-numpy-dep.patch

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - pytorch >=2.2.2,<3.0.0
    - torchvision
    - transformers >=4.42.0,<5.0.0
    - numpy >=1.22,<3.0.0
    - jsonlines >=3.1.0,<4.0.0
    - pillow >=10.0.0,<12.0.0
    - tqdm >=4.64.0,<5.0.0
    - py-opencv >=4.6.0.66,<5.0.0
    - huggingface_hub >=0.23,<1.0.0
    - safetensors >=0.4.3,<1
    - pydantic >=2.0.0,<3
    - docling-core >=2.19.0,<3

tests:
  - python:
      imports:
        - docling_ibm_models
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: This package contains the AI models used by the Docling PDF conversion package
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/DS4SD/docling-ibm-models

extra:
  recipe-maintainers:
    - hadim
